config/routes.rb
Rails.application.routes.draw do
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "pages#home"
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except:[:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord

  has_many :article_categories
  has_many :categories, through: :article_categories
  
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  belongs_to :user

end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase}
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 105 }

  has_many :articles, dependent: :destroy

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user 
  @current_user ||=  User.find(session[:user_id]) if session[:user_id] 
  end

  def logged_in?
    !!current_user
  end
  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform this action"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  # Action to display the detail of specific Article
  def show
    @article = Article.find(params[:id])
  end

  # Action to display all the articles
  def index
    @articles = Article.all
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end

  # Action to create a new article and it is get request
  def new
    @article = Article.new
  end

  # Action to edit any article
  def edit
  end

  # Action to create a new article and it is post request
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = 'Article was created successfully'
      redirect_to @article

    else
      render :new, status: :unprocessable_entity
    end
  end

  # Action to update any article
  def update
    if @article.update(article_params)
      flash[:notice] = 'Article was updated successfully'
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # Action to delete any article
  def destroy
    @article.destroy
    redirect_to articles_path
  end

  # DRY up the code

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit your own article"
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except:[:index, :show]

  def new
    @category = Category.new
  end

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was created successfully"
      redirect_to @category
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category was updated successfully"
      redirect_to @category

      else
        render :edit
    end
  end

  private 
    def category_params 
       params.require(:category).permit(:name)
    end

    def require_admin
      if !(logged_in? && current_user.admin?)
        flash[:notice] = "Only Admin can perform this action"
        redirect_to categories_path
      end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user

    else
      flash.now[:alert] = "There is something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    # @users = User.all
    @users = User.paginate(page: params[:page], per_page: 3)
  end
  def show
    @articles = @user.articles
  end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id

      flash[:notice] = "Welcome #{@user.username}. Your account has been created successfully"
      redirect_to articles_path

    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Account has been updated successfully'
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all asscociated articles successfully deleted"
    redirect_to articles_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  

  
end

app/views/articles/_article.html.erb
<div class="container">
<% @articles.each do |article| %>
<div class="row justify-content-md-center">
<div class="col-8 mt-4">
<div class="card text-center shadow mb-5 bg-white rounded">
  <div class="card-header">
  <% if article.user %>
    by <%= link_to article.user.username, user_path(article.user) %>
  <% end %>
  </div>
  <div class="card-body p-3">

    <% if article.categories.any? %>
      <div class="mt-2"><%= render article.categories %></div><br/>
    <% end %>
    <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
    <p class="card-text"><%= article.description %></p>
    <div class="container">
     <%# <a href="#" class="btn btn-outline-success">View</a> %>
    <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
    <% if logged_in? && (article.user == current_user || current_user.admin?) %>
    <%# <a href="#" class="btn btn-outline-info">Edit</a> %>
    <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
    <%# <a href="#" class="btn btn-outline-danger">Delete</a> %>
    <%= button_to 'Delete', article_path(article), method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}}, 
    class: "btn btn-outline-danger mt-1"  %>
    <% end %>
    </div>
   
  </div>
  <div class="card-footer text-muted">
  <small>Created at <%= time_ago_in_words(article.created_at) %> ago </small>
    
  </div>
</div>
</div>
</div>
<% end %>
</div>

app/views/articles/_form.html.erb
<% if @article.errors.any? %> 
  <h2>The following errors prevented the article from being saved</h2> 
  <ul> 
    <% @article.errors.full_messages.each do |msg| %> 
      <li><%= msg %></li> 
    <% end %> 
  </ul>
<% end %>



<%= form_with(model: @article, local: true) do |f| %>

<p>
<%= f.label :title %><br/>
<%= f.text_field :title %><br/><br/>

<%= f.label :description %><br/>
<%= f.text_area :description %><br/><br/>

<%= f.label :category %><br/>
<%= f.collection_select(:category_ids, Category.all, :id, :name, 
{ prompt: "Make your selection from the list below (can be empty)"}, { multiple: true } ) %><br/><br/>

<%= f.submit%>

</p>

<% end %>

app/views/articles/edit.html.erb
<div class="container p-5">
<h1>Edit Article</h1>

<%= render 'form' %>

<%= link_to 'Cancel and Return to Articles Listing Page', articles_path %>
</div>

app/views/articles/index.html.erb
<h1 class="text-center mt-4 text-white">Listing All the Articles</h1>
<br/>
<%= will_paginate @articles, class: "text-center text-white text-decoration-none p-3" %>
<%= render 'article' %>
<%= will_paginate @articles, class: "text-center text-white text-decoration-none p-3" %>

app/views/articles/new.html.erb
<div class="container border-primary p-5 text-white">
<h1>Create a New Article</h1>


<%= render 'form' %>
<br/>
<%= link_to 'Cancel and Return to Articles Listing Page', articles_path, class: "text-white" %>
</div>

app/views/articles/show.html.erb
<h1 class="text-center text-white mt-2">Showing Article Detail</h1>

<div class="container">
<div class="row justify-content-md-center">
<div class="col-8 mt-4">
<div class="card text-center shadow mb-5 bg-white rounded">
  <div class="card-header">
    by <%= @article.user.username if @article.user %>
  </div>
  <div class="card-body p-3">
  <% if @article.categories.any? %>
  <div class="mt-2"><%= render @article.categories %></div><br/>
  <% end %>
    <h5 class="card-title"><%= link_to @article.title, article_path(@article), class: "text-success" %></h5>
    <p class="card-text"><%= @article.description %></p>
    <div class="container">
     <%# <a href="#" class="btn btn-outline-success">View</a> %>
    <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
    <%# <a href="#" class="btn btn-outline-info">Edit</a> %>
    <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
    <%# <a href="#" class="btn btn-outline-danger">Delete</a> %>
    <%= button_to 'Delete', article_path(@article), method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}}, 
    class: "btn btn-outline-danger mt-1"  %>

    <% end %>
    </div>
   
  </div>
  <div class="card-footer text-muted">
  <small>Created at <%= time_ago_in_words(@article.created_at) %> ago </small>
    
  </div>
</div>
</div>
</div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "bg-info text-decoration-none text-white p-2 mr-1" %><br/>

app/views/categories/_form.html.erb
<% if @category.errors.any? %> 
  <h2>The following errors prevented the article from being saved</h2> 
  <ul> 
    <% @category.errors.full_messages.each do |msg| %> 
      <li><%= msg %></li> 
    <% end %> 
  </ul>
<% end %>



<%= form_with(model: @category, local: true) do |f| %>

<p>
<%= f.label :name %><br/>
<%= f.text_field :name %><br/><br/>

<%= f.submit%>

</p>

<% end %>

app/views/categories/edit.html.erb
<div class="container p-5">
<h1>Edit Category</h1>

<%= render 'form' %>

<%= link_to 'Cancel and Return to Articles Listing Page', articles_path %>
</div>

app/views/categories/index.html.erb
<div class="container">
<% @categories.each do |category| %>
<div class="row justify-content-md-center">
<div class="col-8 mt-4">
<div class="card text-center shadow mb-5 bg-white rounded">
  
  <h5 class="card-title"><%= link_to category.name, category_path(category)%></h5>
  <h5 class="card-title"><%= pluralize(category.articles.count, "article") %></h5>
  
  <div class="card-footer text-muted">
  <small>Created at <%= time_ago_in_words(category.created_at) %></small>
  </div>
</div>
</div>
</div>
<% end %>
</div>

app/views/categories/new.html.erb
<div class="container border-primary p-5 text-white">
<h1>Create a New Category</h1>


<%= render 'form' %>
<br/>
<%= link_to 'Cancel and Return to Categories Listing Page', categories_path, class: "text-white" %>
</div>

app/views/categories/show.html.erb
<div class="container border-primary p-5 text-white text-center">
    <h1><%= @category.name %> Category</h1>
    <div class="container border-primary p-5 text-white text-center">
    
    <% if logged_in? && current_user.admin? %>
    <%= link_to "Edit the Category", edit_category_path(@category), class: "btn btn-outline-info" %>
    <% end %>
    </div>
    <br/>
    <h1>Articles</h1>
     <%= render 'articles/article' %>
    <div class="container text-center">
         <%= link_to 'Cancel and Return to Articles Listing Page', articles_path, class: "text-white" %>
    </div>

    
</div>

app/views/layouts/_footer.html.erb
<div class="card-footer text-muted bg-dark text-light text-center p-3" style="margin-top: 20.5%;">
    @ All Rights Reserved by Alpha Blog
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-dark p-3">
    <div class="container-fluid">
      <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand text-light", id:"logo" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          
          <li class="nav-item">
            <%# <a class="nav-link text-light" href="#"></a> %>
            <%= link_to "Bloggers", users_path, class: "navbar text-light text-decoration-none" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Articles
            </a>
            <ul class="dropdown-menu text-light">
            <% if logged_in? %>
              <li><a class="dropdown-item" href="articles/new"> Create a New Article</a></li>
            <% end %>
              <li class="dropdown-item">
            <%= link_to "View all the Articles", articles_path, class: "text-dark text-decoration-none" %>
          </li>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories
            </a>
            <ul class="dropdown-menu text-light">
            <% if logged_in? && current_user.admin? %>
            <li class="dropdown-item">
              <%= link_to "Create a New Category", new_category_path, class: "text-dark text-decoration-none" %>
            </li>
            <% end %>
              <li class="dropdown-item">
            <%= link_to "View all the Categories", categories_path, class: "text-dark text-decoration-none" %>
          </li>
            </ul>
          </li>

          <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <% ("Admin") if current_user.admin? %>Profile [<%= current_user.username %>]
            </a>
            <div class="dropdown-menu text-light" aria-labelledby="navbar-dropdown" >
              <%= link_to "View your Profile", user_path(current_user), class: "text-dark text-decoration-none" %><br/>
              <%= link_to "Edit your Profile", edit_user_path(current_user), class: "text-dark text-decoration-none" %>
              <%= button_to "Delete your Profile", user_path(current_user), class: "text-danger text-decoration-none",
              method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}} %>
            </div>
          </li>
          <% end %>

          <% if logged_in? %>

          <li class="nav-item">
            <%= link_to current_user.username, user_path(current_user), class: "nav-link text-white btn"%>
          </li>

          <li class="nav-item">
            <%= button_to "Logout", logout_path, class: "nav-link text-white btn", method: :delete %>
          </li>

          <% else %>
           <li class="nav-item">
            <%= link_to "Login", login_path, class: "nav-link text-white btn" %>
          </li>

          <li class="nav-item">
            <%= link_to "Signup", signup_path, class: "nav-link text-white btn" %>
          </li>
          <% end %>
        </ul>
        
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>

    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="stylesheets/custom.css.scss">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <style>
    body{
      background: rgb(60, 60, 60);
      background-repeat: no-repeat;
    }
    </style>
  
  </head>

  <body>

  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  

  
  <%= yield %>
  

  </body>
</html>

app/views/pages/home.html.erb
<div class="container mt-5">
    <div class="jumbotron text-center text-light p-5"> 
        <h1 class="display-4 fw-bold text-center">Hello World! This is Alpha Blog</h1>
        <p class="lead">Welcome to Alpha Blog Website. The World of Articles</p>
        <hr class="my-4">
        <p class="lead">Create and Post your Articles</p>
        <%= link_to "SignUp", signup_path, class: "btn btn-success p-3" %>
    </div>
</div>

<%= render 'layouts/footer' %>

app/views/users/_form.html.erb
<% if @user.errors.any? %> 
  <h2>The following errors prevented the article from being saved</h2> 
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
  <ul> 
    <% @user.errors.full_messages.each do |msg| %> 
      <li><%= msg %></li> 
    <% end %> 
  </ul>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
  
<% end %>

<%= form_with(model: @user, local: true) do |f| %>

<p>
<%= f.label :username %><br/>
<%= f.text_field :username, placeholder: "Enter your username" %><br/><br/>

<%= f.label :email %><br/>
<%= f.email_field :email, placeholder: "Enter your email" %><br/><br>

<%= f.label :password %><br/>
<%= f.password_field :password, placeholder: "Choose a password" %><br/><br/>


<%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class: "btn btn-success") %>

</p>

<% end %>

app/views/users/_user.html.erb
<div class="container">
<% @users.each do |user| %>
<div class="row justify-content-md-center">
<div class="col-8 mt-4">
<div class="card text-center shadow mb-5 bg-white rounded">
  <div class="card-header">
    <%= link_to user.username, user %>
  </div>
  <div class="card-body p-3">
    <h5 class="card-title"><%= pluralize(user.articles.count, "article") %></h5>
    <div class="container">
     <%# <a href="#" class="btn btn-outline-success">View</a> %>
    <%= link_to "View Profile", user, class: "btn btn-outline-success" %>

    <% if logged_in? %>
    <% if user == current_user %>
    <%# <a href="#" class="btn btn-outline-info">Edit</a> %>
    <%= link_to "Edit", edit_user_path(user), class: "btn btn-outline-info" %>
    <% end %>

    <% if current_user.admin? %>
    <%= button_to 'Delete', user_path(user), method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}}, 
    class: "btn btn-outline-danger mt-1"  %>
    <% end %>
    <%# <a href="#" class="btn btn-outline-danger">Delete</a> %>
    <% end %>
    </div>
   
  </div>
  <div class="card-footer text-muted">
  <small>Joined <%= time_ago_in_words(user.created_at) %></small>
    
  </div>
</div>
</div>
</div>
<% end %>
</div>

app/views/users/edit.html.erb
<div class="container border-primary p-5 text-white">
<h1>Edit your account</h1>

<%= render 'form' %>
<br/>
<%= link_to 'Cancel and Return to Articles Listing Page', articles_path, class: "text-white" %>
</div>

app/views/users/index.html.erb
<h1 class="text-center mt-4 text-white">List of All the Users</h1>
<br/>
<%= will_paginate @users, class: "text-center text-white text-decoration-none p-3" %>
<%= render 'user' %>
<%= will_paginate @users, class: "text-center text-white text-decoration-none p-3" %>

app/views/users/new.html.erb
<div class="container border-primary p-5 text-white">
<h1>Signup Form for Alpha Blog</h1>

<%= render 'form' %>
<br/>
<%= link_to 'Cancel and Return to Articles Listing Page', articles_path, class: "text-white" %>
</div>
<%= render 'layouts/footer' %>

app/views/users/show.html.erb
<style>
.container{
  height: auto;
}
</style>

<div class="container border-primary p-5 text-white text-center">
    <h1><%= @user.username %>'s Profile</h1>
    <div class="text-center mt-4">
    <% if logged_in? && @user == current_user %>
    <%= link_to "Edit your Profile", edit_user_path(@user), class: "btn btn-outline-info" %>
    <% end %>
    </div>
    <br/>
    <h1>Articles</h1>
</div>
     <%= render 'articles/article' %>
<div class="container text-center">
     <%= link_to 'Cancel and Return to Articles Listing Page', articles_path, class: "text-white" %>
</div>